version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - SQLALCHEMY_DATABASE_URL=sqlite:///./test.db
    command: uvicorn main:app --host 0.0.0.0 --port 8080
